name: Tests unitaires

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main, production]

jobs:
  tests-unitaires:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Installer les dépendances
        run: pip install -r backend/requirements.txt

      - name: Lancer les tests unitaires
        run: pytest backend/tests/test_unitaire.py -v
        env:
          PYTHONPATH: backend
